# Data Preprocessing

## Objective

This notebook performs data preprocessing on the raw financial datasets collected in the previous notebook.

### Tasks

- Load raw datasets
- Validate files
- Standardize columns
- Convert data types
- Handle missing values
- Remove duplicate records
- Validate OHLCV data
- Detect abnormal values
- Generate preprocessing reports
- Save cleaned datasets

# Imports

In [2]:
from pathlib import Path
import warnings

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

warnings.filterwarnings("ignore")

plt.style.use("seaborn-v0_8")
sns.set_theme(style="whitegrid")

print("Libraries Imported Successfully")

Libraries Imported Successfully

## Configuration

In [3]:
PROJECT_ROOT = Path("..")

RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw"
PROCESSED_DATA_DIR = PROJECT_ROOT / "data" / "processed"

RAW_STOCK_DIR = RAW_DATA_DIR / "stocks"
RAW_INDEX_DIR = RAW_DATA_DIR / "indices"
RAW_ETF_DIR = RAW_DATA_DIR / "etfs"
RAW_COMMODITY_DIR = RAW_DATA_DIR / "commodities"
RAW_FOREX_DIR = RAW_DATA_DIR / "forex"
RAW_MACRO_DIR = RAW_DATA_DIR / "macro"
RAW_NEWS_DIR = RAW_DATA_DIR / "news"

PROCESSED_STOCK_DIR = PROCESSED_DATA_DIR / "stocks"
PROCESSED_INDEX_DIR = PROCESSED_DATA_DIR / "indices"
PROCESSED_ETF_DIR = PROCESSED_DATA_DIR / "etfs"
PROCESSED_COMMODITY_DIR = PROCESSED_DATA_DIR / "commodities"
PROCESSED_FOREX_DIR = PROCESSED_DATA_DIR / "forex"
PROCESSED_MACRO_DIR = PROCESSED_DATA_DIR / "macro"
PROCESSED_NEWS_DIR = PROCESSED_DATA_DIR / "news"

directories = [
    PROCESSED_STOCK_DIR,
    PROCESSED_INDEX_DIR,
    PROCESSED_ETF_DIR,
    PROCESSED_COMMODITY_DIR,
    PROCESSED_FOREX_DIR,
    PROCESSED_MACRO_DIR,
    PROCESSED_NEWS_DIR
]

for directory in directories:
    directory.mkdir(parents=True, exist_ok=True)

print("Directories Ready")

Directories Ready

# Load Dataset

In [4]:
def load_dataset(folder: Path):

    datasets = {}

    csv_files = sorted(folder.glob("*.csv"))

    print(f"Found {len(csv_files)} files\n")

    for file in csv_files:

        try:

            df = pd.read_csv(file)

            datasets[file.stem] = df

            print(f"{file.name:<25} {df.shape}")

        except Exception as e:

            print(file.name, e)

    return datasets

In [5]:
stock_data = load_dataset(RAW_STOCK_DIR)

index_data = load_dataset(RAW_INDEX_DIR)

etf_data = load_dataset(RAW_ETF_DIR)

commodity_data = load_dataset(RAW_COMMODITY_DIR)

forex_data = load_dataset(RAW_FOREX_DIR)

macro_data = load_dataset(RAW_MACRO_DIR)

news_data = load_dataset(RAW_NEWS_DIR)

Found 9 files

AAPL.csv                  (9199, 7)
AMD.csv                   (9199, 7)
AMZN.csv                  (7335, 7)
GOOG.csv                  (5509, 7)
GOOGL.csv                 (5508, 7)
META.csv                  (3557, 7)
MSFT.csv                  (9199, 7)
NVDA.csv                  (6910, 7)
TSLA.csv                  (4034, 7)
Found 5 files

DJI.csv                   (8693, 7)
GSPC.csv                  (9199, 7)
IXIC.csv                  (9199, 7)
RUT.csv                   (9199, 7)
VIX.csv                   (9200, 7)
Found 5 files

QQQ.csv                   (6878, 7)
SOXX.csv                  (6286, 7)
SPY.csv                   (8420, 7)
VGT.csv                   (5648, 7)
XLK.csv                   (6930, 7)
Found 8 files

CL=F.csv                  (6498, 7)
CL_F.csv                  (6499, 7)
GC=F.csv                  (6489, 7)
GC_F.csv                  (6490, 7)
NG=F.csv                  (6495, 7)
NG_F.csv                  (6496, 7)
SI=F.csv                  (6491, 7)
SI_F.csv                  (6492, 7)
Found 8 files

EURUSD=X.csv              (5867, 7)
EURUSD_X.csv              (5869, 7)
GBPUSD=X.csv              (5879, 7)
GBPUSD_X.csv              (5881, 7)
JPY=X.csv                 (7701, 7)
JPY_X.csv                 (7703, 7)
USDCNY=X.csv              (6269, 7)
USDCNY_X.csv              (6271, 7)
Found 11 files

CPI.csv                   (437, 2)
DOLLAR_INDEX.csv          (5355, 2)
FED_FUNDS_RATE.csv        (438, 2)
FED_RATE.csv              (438, 2)
GDP.csv                   (145, 2)
INDUSTRIAL_PRODUCTION.csv (437, 2)
PPI.csv                   (437, 2)
RECESSION.csv             (438, 2)
TREASURY_10Y.csv          (438, 2)
UNEMPLOYMENT.csv          (438, 2)
UNEMPLOYMENT_RATE.csv     (438, 2)
Found 8 files

AAPL_news.csv             (10, 2)
AMD_news.csv              (10, 2)
AMZN_news.csv             (10, 2)
GOOG_news.csv             (10, 2)
META_news.csv             (10, 2)
MSFT_news.csv             (10, 2)
NVDA_news.csv             (10, 2)
TSLA_news.csv             (10, 2)

# Dataset Information

In [6]:
for name, df in stock_data.items():

    print("=" * 70)

    print(name)

    display(df.head())

    print(df.info())

======================================================================
AAPL

,Date,Adj Close,Close,High,Low,Open,Volume
0,NaN,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL
1,1990-01-02,0.2604654133319855,0.3325890004634857,0.3348209857940674,0.3125,0.31473198533058167,183198400
2,1990-01-03,0.26221320033073425,0.3348209857940674,0.3392859995365143,0.3348209857940674,0.3392859995365143,207995200
3,1990-01-04,0.2630879878997803,0.3359380066394806,0.34598198533058167,0.3325890004634857,0.34151801466941833,221513600
4,1990-01-05,0.263962060213089,0.3370540142059326,0.34151801466941833,0.33035698533058167,0.3370540142059326,123312000

<class 'pandas.DataFrame'>
RangeIndex: 9199 entries, 0 to 9198
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       9198 non-null   str
 1   Adj Close  9199 non-null   str
 2   Close      9199 non-null   str
 3   High       9199 non-null   str
 4   Low        9199 non-null   str
 5   Open       9199 non-null   str
 6   Volume     9199 non-null   str
dtypes: str(7)
memory usage: 1.4 MB
None
======================================================================
AMD

         Date Adj Close   Close    High     Low    Open   Volume
0         NaN       AMD     AMD     AMD     AMD     AMD      AMD
1  1990-01-02     4.125   4.125   4.125  3.8125  3.9375  2544000
2  1990-01-03       4.0     4.0   4.125  3.9375  4.0625   686800
3  1990-01-04    3.9375  3.9375  4.0625   3.875     4.0   944200
4  1990-01-05    3.8125  3.8125  3.8125  3.6875  3.8125  1511000

<class 'pandas.DataFrame'>
RangeIndex: 9199 entries, 0 to 9198
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       9198 non-null   str
 1   Adj Close  9199 non-null   str
 2   Close      9199 non-null   str
 3   High       9199 non-null   str
 4   Low        9199 non-null   str
 5   Open       9199 non-null   str
 6   Volume     9199 non-null   str
dtypes: str(7)
memory usage: 1.2 MB
None
======================================================================
AMZN

,Date,Adj Close,Close,High,Low,Open,Volume
0,NaN,AMZN,AMZN,AMZN,AMZN,AMZN,AMZN
1,1997-05-15,0.09791699796915054,0.09791699796915054,0.125,0.09635400027036667,0.12187500298023224,1443120000
2,1997-05-16,0.0864579975605011,0.0864579975605011,0.09895800054073334,0.0854170024394989,0.09843800216913223,294000000
3,1997-05-19,0.0854170024394989,0.0854170024394989,0.08854199945926666,0.08124999701976776,0.08802100270986557,122136000
4,1997-05-20,0.08177100121974945,0.08177100121974945,0.08749999850988388,0.08177100121974945,0.0864579975605011,109344000

<class 'pandas.DataFrame'>
RangeIndex: 7335 entries, 0 to 7334
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       7334 non-null   str
 1   Adj Close  7335 non-null   str
 2   Close      7335 non-null   str
 3   High       7335 non-null   str
 4   Low        7335 non-null   str
 5   Open       7335 non-null   str
 6   Volume     7335 non-null   str
dtypes: str(7)
memory usage: 1.1 MB
None
======================================================================
GOOG

,Date,Adj Close,Close,High,Low,Open,Volume
0,NaN,GOOG,GOOG,GOOG,GOOG,GOOG,GOOG
1,2004-08-19,2.4772913455963135,2.4991331100463867,2.591784954071045,2.3900420665740967,2.490664005279541,897427216
2,2004-08-20,2.674062490463257,2.697638988494873,2.7168169021606445,2.5031180381774902,2.515820026397705,458857488
3,2004-08-23,2.7009732723236084,2.7247869968414307,2.8264060020446777,2.7160699367523193,2.758410930633545,366857939
4,2004-08-24,2.589132308959961,2.611959934234619,2.779581069946289,2.5795810222625732,2.7706151008605957,306396159

<class 'pandas.DataFrame'>
RangeIndex: 5509 entries, 0 to 5508
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       5508 non-null   str
 1   Adj Close  5509 non-null   str
 2   Close      5509 non-null   str
 3   High       5509 non-null   str
 4   Low        5509 non-null   str
 5   Open       5509 non-null   str
 6   Volume     5509 non-null   str
dtypes: str(7)
memory usage: 864.4 KB
None
======================================================================
GOOGL

,Date,Adj Close,Close,High,Low,Open,Volume
0,NaN,GOOGL,GOOGL,GOOGL,GOOGL,GOOGL,GOOGL
1,2004-08-19,2.488940715789795,2.5110108852386475,2.6041040420532227,2.4014010429382324,2.502502918243408,893181924
2,2004-08-20,2.6866371631622314,2.7104599475860596,2.7297298908233643,2.515014886856079,2.527777910232544,456686856
3,2004-08-23,2.7136752605438232,2.7377378940582275,2.8398399353027344,2.7289791107177734,2.771522045135498,365122512
4,2004-08-24,2.6013076305389404,2.6243739128112793,2.792793035507202,2.59184193611145,2.7837839126586914,304946748

<class 'pandas.DataFrame'>
RangeIndex: 5508 entries, 0 to 5507
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       5507 non-null   str
 1   Adj Close  5508 non-null   str
 2   Close      5508 non-null   str
 3   High       5508 non-null   str
 4   Low        5508 non-null   str
 5   Open       5508 non-null   str
 6   Volume     5508 non-null   str
dtypes: str(7)
memory usage: 863.1 KB
None
======================================================================
META

,Date,Adj Close,Close,High,Low,Open,Volume
0,NaN,META,META,META,META,META,META
1,2012-05-18,37.8972053527832,38.22999954223633,45.0,38.0,42.04999923706055,573576400
2,2012-05-21,33.733760833740234,34.029998779296875,36.65999984741211,33.0,36.529998779296875,168192700
3,2012-05-22,30.73014259338379,31.0,33.59000015258789,30.940000534057617,32.61000061035156,101786600
4,2012-05-23,31.721437454223633,32.0,32.5,31.360000610351562,31.3700008392334,73600000

<class 'pandas.DataFrame'>
RangeIndex: 3557 entries, 0 to 3556
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       3556 non-null   str
 1   Adj Close  3557 non-null   str
 2   Close      3557 non-null   str
 3   High       3557 non-null   str
 4   Low        3557 non-null   str
 5   Open       3557 non-null   str
 6   Volume     3557 non-null   str
dtypes: str(7)
memory usage: 543.8 KB
None
======================================================================
MSFT

,Date,Adj Close,Close,High,Low,Open,Volume
0,NaN,MSFT,MSFT,MSFT,MSFT,MSFT,MSFT
1,1990-01-02,0.374813050031662,0.6163190007209778,0.6163190007209778,0.5980899930000305,0.6059030294418335,53035200
2,1990-01-03,0.37692511081695557,0.6197919845581055,0.6267359852790833,0.6145830154418945,0.6215280294418335,113774400
3,1990-01-04,0.3880111277103424,0.6380209922790527,0.6388890147209167,0.6163190007209778,0.6197919845581055,125740800
4,1990-01-05,0.3785087466239929,0.6223959922790527,0.6388890147209167,0.6215280294418335,0.6354169845581055,69566400

<class 'pandas.DataFrame'>
RangeIndex: 9199 entries, 0 to 9198
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       9198 non-null   str
 1   Adj Close  9199 non-null   str
 2   Close      9199 non-null   str
 3   High       9199 non-null   str
 4   Low        9199 non-null   str
 5   Open       9199 non-null   str
 6   Volume     9199 non-null   str
dtypes: str(7)
memory usage: 1.3 MB
None
======================================================================
NVDA

,Date,Adj Close,Close,High,Low,Open,Volume
0,NaN,NVDA,NVDA,NVDA,NVDA,NVDA,NVDA
1,1999-01-22,0.037559062242507935,0.041016001254320145,0.04882799834012985,0.038802001625299454,0.04374999925494194,2714688000
2,1999-01-25,0.041493915021419525,0.04531300067901611,0.04583299905061722,0.041016001254320145,0.04427099972963333,510480000
3,1999-01-26,0.03827424347400665,0.04179700091481209,0.046744998544454575,0.04114599898457527,0.04583299905061722,343200000
4,1999-01-27,0.03815518692135811,0.04166699945926666,0.04296899959445,0.0395830012857914,0.041926998645067215,244368000

<class 'pandas.DataFrame'>
RangeIndex: 6910 entries, 0 to 6909
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       6909 non-null   str
 1   Adj Close  6910 non-null   str
 2   Close      6910 non-null   str
 3   High       6910 non-null   str
 4   Low        6910 non-null   str
 5   Open       6910 non-null   str
 6   Volume     6910 non-null   str
dtypes: str(7)
memory usage: 1.1 MB
None
======================================================================
TSLA

,Date,Adj Close,Close,High,Low,Open,Volume
0,NaN,TSLA,TSLA,TSLA,TSLA,TSLA,TSLA
1,2010-06-29,1.5926669836044312,1.5926669836044312,1.6666669845581055,1.1693329811096191,1.2666670083999634,281494500
2,2010-06-30,1.5886670351028442,1.5886670351028442,2.0280001163482666,1.553333044052124,1.7193330526351929,257806500
3,2010-07-01,1.4639999866485596,1.4639999866485596,1.7280000448226929,1.3513330221176147,1.6666669845581055,123282000
4,2010-07-02,1.2799999713897705,1.2799999713897705,1.5399999618530273,1.24733304977417,1.5333329439163208,77097000

<class 'pandas.DataFrame'>
RangeIndex: 4034 entries, 0 to 4033
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       4033 non-null   str
 1   Adj Close  4034 non-null   str
 2   Close      4034 non-null   str
 3   High       4034 non-null   str
 4   Low        4034 non-null   str
 5   Open       4034 non-null   str
 6   Volume     4034 non-null   str
dtypes: str(7)
memory usage: 631.0 KB
None

## Standardize Column Names

In [7]:
def clean_columns(df):

    df.columns = (
        df.columns
        .str.strip()
        .str.replace(" ", "_")
        .str.replace("-", "_")
    )

    return df

In [8]:
for datasets in [
    stock_data,
    index_data,
    etf_data,
    commodity_data,
    forex_data,
    macro_data,
    news_data
]:

    for key in datasets:

        datasets[key] = clean_columns(datasets[key])

print("Columns Standardized")

Columns Standardized